#/srv/docker/containers/

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /srv/docker/containers/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup
    networks:
      - default

  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    volumes:
      - /srv/docker/containers/adguardhome/data:/opt/adguardhome/work
      - /srv/docker/containers/adguardhome/config:/opt/adguardhome/conf
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "6868:68/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
      - "784:784/udp"
      - "853:853/tcp"
      - "853:853/udp"
      - "3000:3000/tcp"
      - "5443:5443/tcp"
      - "5443:5443/udp"
      - "8853:8853/udp"
    networks:
      - default

networks:
  default:
    driver: bridge
